export const columns = [
  { key: "kode_satker", label: "Kode Satker", rowSpan: 3 },
  {
    label: "Eselon",
    key: "eselon",
    rowSpan: 2,
  },
  {
    label: "Kualitas Perencanaan Anggaran",
    children: [
      { key: "revisi_dipa", label: "Revisi DIPA" },
      { key: "deviasi_hal3_dipa", label: "Deviasi Hal III Dipa" },
    ],
  },
  {
    label: "Kualitas Pelaksanaan Anggaran",
    children: [
      { key: "realisasi_anggaran", label: "Realisasi Anggaran" },
      { key: "belanja_kontraktual", label: "Belanja Kontraktual" },
      { key: "penyelesaian_tagihan", label: "Penyelesaian Tagihan" },
      { key: "pengelolaan_up_tup", label: "Pengelolaan UP TUP" },
    ],
  },
  {
    label: "Kualitas Hasil Pelaksanaan Anggaran",
    children: [{ key: "capaian_output", label: "Capaian Output" }],
  },
  { key: "nilai_ikpa", label: "Nilai IKPA", rowSpan: 10 },
  { key: "dispensasi_spm", label: "Dispensasi SPM", rowSpan: 11 },
];

export const dummyGroupedData = {
  E1: {
    parent: {
      eselon_code: "E1",
      name: "Sekretariat Jenderal",
      revisi_dipa: 90.2,
      deviasi_hal3_dipa: 88.5,
      realisasi_anggaran: 92.1,
      belanja_kontraktual: 91.4,
      penyelesaian_tagihan: 89.9,
      pengelolaan_up_tup: 93.3,
      capaian_output: 94.1,
      nilai_ikpa: 91.8,
      dispensasi_spm: 1,
      tanggal_sumber_data: "2026-01-20",
    },
    children: [
      {
        id: 1,
        satker_code: "E1-001",
        name: "Biro Perencanaan",
        revisi_dipa: 89,
        deviasi_hal3_dipa: 87,
        realisasi_anggaran: 90,
        belanja_kontraktual: 91,
        penyelesaian_tagihan: 88,
        pengelolaan_up_tup: 92,
        capaian_output: 93,
        nilai_ikpa: 90.2,
        dispensasi_spm: 0,
        tanggal_sumber_data: "2026-01-20",
      },
      {
        id: 2,
        satker_code: "E1-002",
        name: "Biro Keuangan",
        revisi_dipa: 91,
        deviasi_hal3_dipa: 90,
        realisasi_anggaran: 92,
        belanja_kontraktual: 93,
        penyelesaian_tagihan: 90,
        pengelolaan_up_tup: 94,
        capaian_output: 95,
        nilai_ikpa: 93.4,
        dispensasi_spm: 1,
        tanggal_sumber_data: "2026-01-20",
      },
      {
        id: 3,
        satker_code: "E1-003",
        name: "Biro Umum",
        revisi_dipa: 85,
        deviasi_hal3_dipa: 84,
        realisasi_anggaran: 86,
        belanja_kontraktual: 87,
        penyelesaian_tagihan: 85,
        pengelolaan_up_tup: 88,
        capaian_output: 89,
        nilai_ikpa: 86.8,
        dispensasi_spm: 2,
        tanggal_sumber_data: "2026-01-20",
      },
      {
        id: 4,
        satker_code: "E1-004",
        name: "Biro SDM",
        revisi_dipa: 93,
        deviasi_hal3_dipa: 92,
        realisasi_anggaran: 94,
        belanja_kontraktual: 95,
        penyelesaian_tagihan: 93,
        pengelolaan_up_tup: 96,
        capaian_output: 97,
        nilai_ikpa: 95.1,
        dispensasi_spm: 0,
        tanggal_sumber_data: "2026-01-20",
      },
      {
        id: 5,
        satker_code: "E1-005",
        name: "Biro Hukum",
        revisi_dipa: 80,
        deviasi_hal3_dipa: 79,
        realisasi_anggaran: 82,
        belanja_kontraktual: 81,
        penyelesaian_tagihan: 80,
        pengelolaan_up_tup: 83,
        capaian_output: 84,
        nilai_ikpa: 81.7,
        dispensasi_spm: 3,
        tanggal_sumber_data: "2026-01-20",
      },
    ],
  },

  E2: {
    parent: {
      eselon_code: "E2",
      name: "Inspektorat Jenderal",
      revisi_dipa: 90.2,
      deviasi_hal3_dipa: 88.5,
      realisasi_anggaran: 92.1,
      belanja_kontraktual: 91.4,
      penyelesaian_tagihan: 89.9,
      pengelolaan_up_tup: 93.3,
      capaian_output: 94.1,
      nilai_ikpa: 91.8,
      dispensasi_spm: 0,
      tanggal_sumber_data: "2026-01-20",
    },
    children: [
      {
        id: 6,
        satker_code: "E2-001",
        name: "Inspektorat I",
        revisi_dipa: 95,
        deviasi_hal3_dipa: 94,
        realisasi_anggaran: 96,
        belanja_kontraktual: 97,
        penyelesaian_tagihan: 95,
        pengelolaan_up_tup: 98,
        capaian_output: 99,
        nilai_ikpa: 97.2,
        dispensasi_spm: 0,
        tanggal_sumber_data: "2026-01-20",
      },
      {
        id: 7,
        satker_code: "E2-002",
        name: "Inspektorat II",
        revisi_dipa: 92,
        deviasi_hal3_dipa: 91,
        realisasi_anggaran: 93,
        belanja_kontraktual: 94,
        penyelesaian_tagihan: 92,
        pengelolaan_up_tup: 95,
        capaian_output: 96,
        nilai_ikpa: 94.6,
        dispensasi_spm: 1,
        tanggal_sumber_data: "2026-01-20",
      },
      {
        id: 8,
        satker_code: "E2-003",
        name: "Inspektorat III",
        revisi_dipa: 88,
        deviasi_hal3_dipa: 87,
        realisasi_anggaran: 89,
        belanja_kontraktual: 90,
        penyelesaian_tagihan: 88,
        pengelolaan_up_tup: 91,
        capaian_output: 92,
        nilai_ikpa: 89.3,
        dispensasi_spm: 2,
        tanggal_sumber_data: "2026-01-20",
      },
      {
        id: 9,
        satker_code: "E2-004",
        name: "Inspektorat IV",
        revisi_dipa: 96,
        deviasi_hal3_dipa: 95,
        realisasi_anggaran: 97,
        belanja_kontraktual: 98,
        penyelesaian_tagihan: 96,
        pengelolaan_up_tup: 99,
        capaian_output: 100,
        nilai_ikpa: 98.4,
        dispensasi_spm: 0,
        tanggal_sumber_data: "2026-01-20",
      },
      {
        id: 10,
        satker_code: "E2-005",
        name: "Inspektorat V",
        revisi_dipa: 83,
        deviasi_hal3_dipa: 82,
        realisasi_anggaran: 84,
        belanja_kontraktual: 85,
        penyelesaian_tagihan: 83,
        pengelolaan_up_tup: 86,
        capaian_output: 87,
        nilai_ikpa: 84.1,
        dispensasi_spm: 4,
        tanggal_sumber_data: "2026-01-20",
      },
    ],
  },
};
