export const dashboardCards = [
  { title: "Seletariat Jenderal", value: "95.29", color: "bg-[#6FCE00]" },
  { title: "Inspektorat Jenderal", value: "95.29", color: "bg-[#6FCE00]" },
  { title: "Ditjen Banapenta dan PKK", value: "95.29", color: "bg-[#F1E528]" },
  { title: "PHI dan Jamsostek", value: "95.29", color: "bg-[#2E70FD]" },
  { title: "Binwasnaker dan K3", value: "95.29", color: "bg-[#6FCE00]" },
  { title: "Barenbang Ketenagakerjaan", value: "95.29", color: "bg-[#6FCE00]" },
  { title: "Binalavotas", value: "95.29", color: "bg-[#6FCE00]" },
];

export const dataTable = {
  columns: [
    { label: "Eselon 1", key: "Eselon 1" },
    { label: "Revisi DIPA (10%)", key: "Revisi DIPA (10%)" },
    { label: "Deviasi Hal III Dipa (15%)", key: "Deviasi Hal III Dipa (15%)" },
    { label: "Realisasi Anggaran (20%)", key: "Realisasi Anggaran (20%)" },
    { label: "Belanja Kontraktual (10%)", key: "Belanja Kontraktual (10%)" },
    { label: "Penyelesaian Tagihan (10%)", key: "Penyelesaian Tagihan (10%)" },
    { label: "Pengelolaan UP & TUP (10%)", key: "Pengelolaan UP & TUP (10%)" },
    { label: "Capaian Output (25%)", key: "Capaian Output (25%)" },
    {
      label: "Nilai IKPA",
      key: "Nilai IKPA",
      style: "bg-[#2E70FD] rounded p-2 text-white",
    },
  ],
  data: [
    {
      eselon: "Sekretariat Jenderal",
      revisiDipa: 100,
      deviasiHalIII: 94,
      realisasiAnggaran: 81.83,
      belanjaKontraktual: 100,
      penyelesaianTagihan: 100,
      pengelolaanUPTUP: 98.21,
      capaianOutput: 100,
      nilaiIKPA: 95.29,
    },
    {
      eselon: "Inspektorat Jenderal",
      revisiDipa: 100,
      deviasiHalIII: 92.68,
      realisasiAnggaran: 93.13,
      belanjaKontraktual: 100,
      penyelesaianTagihan: 100,
      pengelolaanUPTUP: 97,
      capaianOutput: 100,
      nilaiIKPA: 97.23,
    },
    {
      eselon: "Ditjen Binapenta",
      revisiDipa: 100,
      deviasiHalIII: 81.9,
      realisasiAnggaran: 82.01,
      belanjaKontraktual: 100,
      penyelesaianTagihan: 100,
      pengelolaanUPTUP: 99.72,
      capaianOutput: 100,
      nilaiIKPA: 93.66,
    },
    {
      eselon: "PHI dan Jamsostek",
      revisiDipa: 100,
      deviasiHalIII: 67.87,
      realisasiAnggaran: 100,
      belanjaKontraktual: 100,
      penyelesaianTagihan: 100,
      pengelolaanUPTUP: 100,
      capaianOutput: 100,
      nilaiIKPA: 95.18,
    },
    {
      eselon: "Binwasnaker dan K3",
      revisiDipa: 100,
      deviasiHalIII: 81.46,
      realisasiAnggaran: 79.34,
      belanjaKontraktual: 100,
      penyelesaianTagihan: 100,
      pengelolaanUPTUP: 99.85,
      capaianOutput: 100,
      nilaiIKPA: 93.07,
    },
    {
      eselon: "Barenbang Ketenagakerjaan",
      revisiDipa: 100,
      deviasiHalIII: 74.25,
      realisasiAnggaran: 79.37,
      belanjaKontraktual: 100,
      penyelesaianTagihan: 100,
      pengelolaanUPTUP: 96.29,
      capaianOutput: 100,
      nilaiIKPA: 83.99,
    },
    {
      eselon: "Binalavotas",
      revisiDipa: 100,
      deviasiHalIII: 75.61,
      realisasiAnggaran: 82.1,
      belanjaKontraktual: 100,
      penyelesaianTagihan: 100,
      pengelolaanUPTUP: 95.56,
      capaianOutput: 97.68,
      nilaiIKPA: 69,
    },
    {
      eselon: "Kementerian",
      revisiDipa: 100,
      deviasiHalIII: 70.41,
      realisasiAnggaran: 99.78,
      belanjaKontraktual: 100,
      penyelesaianTagihan: 100,
      pengelolaanUPTUP: 97.33,
      capaianOutput: 98.63,
      nilaiIKPA: 94.91,
    },
  ],
};
